---
- name: Configure AWS resources
  hosts: ec2-13-127-90-160.ap-south-1.compute.amazonaws.com
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Ensure Nginx service is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create HTML file for default webpage
      copy:
        content: "<html><body><h1>Welcome to My Website!</h1></body></html>"
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Restart Nginx service to apply changes
      service:
        name: nginx
        state: restarted